### ISSUE TITLE
i got error

### ISSUE THREAD

**Issue by mehranexpert** [Kladdkaka/ProxyGrabber#2]
```
python proxy_grabber.py 
  File "proxy_grabber.py", line 43
    print('get proxies from', name, end='\r')
                                       ^
SyntaxError: invalid syntax

```

also in Pytho3

```
# python3 proxy_grabber.py 
Traceback (most recent call last):
  File "proxy_grabber.py", line 9, in <module>
    from pyquery import PyQuery
ImportError: No module named 'pyquery'

```

**Comment by Kladdkaka** [comment]
you need to run python 3 i believe, and do "pip install pyquery"! =)
